/*
* Datensätze der Entitys Hersteller und Parfum
*/

INSERT INTO HERSTELLER (NAME) VALUES ('Lancôme');
INSERT INTO HERSTELLER (NAME) VALUES ('Hugo Boss');
INSERT INTO HERSTELLER (NAME) VALUES ('Marc Jacobs');

INSERT INTO PARFUM (HERSTELLER_ID, NAME, PREIS, GROESSE, BESCHREIBUNG) VALUES (1, 'La Vie est Belle', 85.0, 85, 'blumig');
INSERT INTO PARFUM (HERSTELLER_ID, NAME, PREIS, GROESSE, BESCHREIBUNG) VALUES (2, 'BOSS Bottled', 35.0, 100, 'herb');
INSERT INTO PARFUM (HERSTELLER_ID, NAME, PREIS, GROESSE, BESCHREIBUNG) VALUES (3, 'Daisy', 90.0, 85, 'blumig, fruchtig');
INSERT INTO PARFUM (HERSTELLER_ID, NAME, PREIS, GROESSE, BESCHREIBUNG) VALUES (1, 'Hypnôse Homme', 48.95, 50, 'frisch');